import Head from 'next/head'
import Image from 'next/image'
import Loader from '../components/Loader'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Firebase Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Loader show/>
    </div>
  )
}
